//------------------------------------------------------------------------------
// <auto-generated>
//    This code is auto-generated by a T4 template. This class can be only customized modifying the corresponding partial class.
//    All other changes to this file will cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AutoEcMvc.Models
{
    public partial class Course
    {

        [DatabaseGenerated(DatabaseGeneratedOption.None)]

        [Display(Name = "Number")]

        public int CourseID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }

        [Range(0, 5)]
        public int Credits { get; set; }

        public int DepartmentID { get; set; }
        public Department Department { get; set; }


        public ICollection<Enrollment> Enrollments { get; set; }


        public ICollection<CourseAssignment> CourseAssignments { get; set; }

    }
}
